server.port = 9092
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.show-sql=true
springdoc.swagger-ui.path= /docs
resilience4j.circuitbreaker.instances.patient_service.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.patient_service.slidingWindowSize=5
resilience4j.circuitbreaker.instances.patient_service.failureRateThreshold=50
resilience4j.circuitbreaker.instances.patient_service.waitDurationInOpenState=10000
resilience4j.retry.instance.Patient_Retry.maxAttempts=5
resilience4j.retry.instance.Patient_Retry.wait-duration=1s
resilience4j.retry.instance.Patient_Retry.enable-exponential-backoff=true
