spring.application.name=hospitalgateway
server.port=8762

spring.config.import=optional:configserver:http://config-server:8888

eureka.client.service-url.defaultZone=http://eureka:8761/eureka/

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://auth-service:1000
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://auth-service:1000/oauth2/jwks