spring.application.name=appointment
server.port = 8083
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.jpa.show-sql=true
#springdoc.swagger-ui.path= /docs
#resilience4j.circuitbreaker.instances.patient_service.registerHealthIndicator=true
#resilience4j.circuitbreaker.instances.patient_service.slidingWindowSize=5
#resilience4j.circuitbreaker.instances.patient_service.failureRateThreshold=50
#resilience4j.circuitbreaker.instances.patient_service.waitDurationInOpenState=10000
#resilience4j.retry.instance.Patient_Retry.maxAttempts=5
#resilience4j.retry.instance.Patient_Retry.wait-duration=1s
#resilience4j.retry.instance.Patient_Retry.enable-exponential-backoff=true
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.config.import = optional:configserver:http://localhost:8888
spring.cloud.stream.bindings.appointmentCreated-out-0.destination=appointment.created
spring.cloud.stream.bindings.appointmentCreated-out-0.contentType=application/json
spring.cloud.stream.bindings.appointmentCreated-out-0.group=${spring.application.name}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:1000/oauth2/jwks
spring.datasource.url=jdbc:postgresql://localhost:5433/hospital
spring.datasource.username=postgres
spring.datasource.password=deepak9089
