spring.application.name=patient
server.port =8081
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.jpa.show-sql=true
#springdoc.swagger-ui.path= /docs
spring.config.import = optional:configserver:http://localhost:8888
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.cloud.stream.function.definition=appointmentCreated
spring.cloud.stream.bindings.appointmentCreated-in-0.destination=appointment.created
spring.cloud.stream.bindings.appointmentCreated-in-0.group=patient-service
spring.cloud.stream.bindings.appointmentCreated-in-0.contentType=application/json