spring.application.name=department
server.port = 8084
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.jpa.show-sql=true
#springdoc.swagger-ui.path= /docs
spring.config.import = optional:configserver:http://localhost:8888
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:1000/oauth2/jwks
spring.datasource.url=jdbc:postgresql://localhost:5433/hospital
spring.datasource.username=postgres
spring.datasource.password=deepak9089